# Service
# LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: my-service-lb
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080

This service creates an external load balancer that forwards traffic to the pods selected by the app: my-app label. It listens on port 80 and forwards requests to port 8080 on the pods.

# ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: my-service-clusterip
spec:
  selector:
    app: my-app
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080

This service creates an internal virtual IP address that forwards traffic to the pods selected by the app: my-app label. It listens on port 80 and forwards requests to port 8080 on the pods.


# NodePort

apiVersion: v1
kind: Service
metadata:
  name: my-service-nodeport
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080

# This service creates a port on each node in the cluster that forwards traffic to the pods selected by the app: my-app label. It listens on port 30080 on each node and forwards requests to port 8080 on the pods.